# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testNanoLog_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#s.static_framework = true
  # Pods for testNanoLog_ios

source 'git@git.corp.kuaishou.com:ios/dependents.git'
pod 'Obiwan', '~> 2.0.0'

  target 'testNanoLog_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testNanoLog_iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
